baseURL = ""
languageCode = 'en-us'
theme = "coming-soon"

[params]
    title = "Coming Soon Hugo"
    description = "A simple countdown"
    favicon = ""
    message = "COMING SOON!"
    release = "July 30, 2024"
    background = ""

socialIcons = [
    {name = "email", url = "example@example.com"},
    {name = "github", url = "https://github.com/"},
        {name = "linkedin", url = "https://linkedin.com/"},
]

[params.twitter]
	enable = false 
	username = "mansoorbarri"
